### ISSUE TITLE
"Requires(pre)" and "Requires(preun)" being ignored in subpackages

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#50]
I'm not sure what's going on, but my `Requires(pre)` and `Requires(preun)` lines aren't being translated into `Pre-Depends`. In fact, they're just being ignored.

**Comment by Conan-Kudo** [comment]
It's still not working with `debbuild-16.10.1`.

**Comment by Conan-Kudo** [comment]
Adding 1a4401ee88d039c49082fe782d742fff913b71a2 doesn't fix it either.

**Comment by ascherer** [comment]
Can you provide a small example, please?

I built your zfs.spec with "Requires(pre): ...", and "Pre-Depends: ..." showd up in the package's "control" script.

**Comment by Conan-Kudo** [comment]
@ascherer I sent you via email my spec with the line being ignored in place.

**Comment by Conan-Kudo** [comment]
@ascherer I've verified this is properly fixed as of the current git master.

**Comment by ascherer** [comment]
For starters, I think this will be quite hard to **bisect**, because of the uncountable internal changes in `debbuild` and its environment.

I've just tried version **16.10.2** from the local git repo, and it fails with the installed **19.11.0**  `macros` (missing `%{verbose:set -x}...` syntax).

Good luck!
