### ISSUE TITLE
Macros aren't getting evaluated in %description section

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#70]
When building RPMs, macros are generally evaluated in the `%description` section.

For example, the `%description` section for `dattobd-utils` in [dattobd.spec](https://github.com/datto/dattobd/blob/master/dist/dattobd.spec) is the following:

```rpm-spec
%description utils
Utilities for %{name} to use the kernel module.
```

In the above case, `rpmbuild` renders it as: `Utilities for dattobd to use the kernel module.`

However, `debbuild` does not do this and stores it as-is.

**Comment by ascherer** [comment]
I had removed macro expansion [earlier](https://github.com/ascherer/debbuild/commit/2587b402c3c6a8434212a23c934a38db416cd60f) due to repeatedly occuring problems. Now it seems that the recent code simplifications permit to expand simple macros in the `%description`. I hope this doesn't break something else.
