### ISSUE TITLE
`%%` doesn't work for using literal `%` somewhere

### ISSUE THREAD

**Issue by Conan-Kudo** [ascherer/debbuild#75]
In rpmbuild, `%%` can be used to indicate that `%` is a literal rather than the indicator of a macro. Thus, it's an escape marker. debbuild seems to ignore this, and this is a problem for when you need to use `%` literally in a spec.

**Comment by ascherer** [comment]
Yeah, I struggled quite a bit with the single word `%patch` in the `%description` section of `debbuild.spec`, until I decided _not_ to expand macros here at all.

I'll try to study `rpmbuild`'s behavior and adapt `debbuild` accordingly.

**Comment by ascherer** [comment]
If I see it correctly, `rpmbuild` replaces any **pair** of percent signs by a **single percent** sign _once_, i.e. `%` and `%%` both yield `%`, `%%%` and `%%%%` both yield `%%`, etc.

This seems tricky to reproduce in `debbuild`, because of the possibly recursive calls to `expandmacros()`. There is already the [code for reducing level of macronization](https://github.com/ascherer/debbuild/blob/master/debbuild#L1816) in place. Adding more special-case treatment most likely will backfire.
